baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'scikit-build'
theme = 'github.com/adityatelange/hugo-PaperMod'

[params]
  description = "Build tools for Python extensions using CMake"
  defaultTheme = "auto"
  hideMeta = true

  [params.assets]
    favicon = "/favicon.png"
    favicon16x16 = "/favicon.png"
    favicon32x32 = "/favicon.png"
    apple_touch_icon = "/favicon.png"

  [params.label]
    text = ""
    icon = "images/scikit_build_mark.svg"
    iconHeight = 36

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/#projects"
    weight = 10
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 15
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/scikit-build"
    weight = 20

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
